### ISSUE TITLE
No such file error during processing

### ISSUE THREAD

**Issue by megedoherty** [ahoog42/ios-triage#13]
We were using a jailbroken iPhone 6 with iOS 8.4. The extraction completed successfully, but the process step produced the following error:

`xadmin@ubuntu:~$ ios-triage process /home/xadmin/Documents/af0c4c26a9c3d26093ef58922823749a02d1eaf0/1508941979989/
7:34:25 AM - info: executing processArtifacts now
7:34:25 AM - info: Backup dir not found, skipping processing
7:34:25 AM - info: wrote app data to disk
7:34:25 AM - info: wrote device info and domains to disk
7:34:25 AM - info: wrote pprofile data to disk
7:34:25 AM - info: wrote parsed backup data to disk
7:34:25 AM - info: wrote syslog data to disk
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/home/xadmin/Documents/af0c4c26a9c3d26093ef58922823749a02d1eaf0/1508941979989/artifacts/crash_reports/ExcResource_FlightApp'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Stream.<anonymous> (/home/xadmin/ios-triage/index.js:944:30)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at drain (/home/xadmin/ios-triage/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/home/xadmin/ios-triage/node_modules/through/index.js:45:5)
    at Stream.<anonymous> (/home/xadmin/ios-triage/node_modules/split/index.js:61:10)
    at _end (/home/xadmin/ios-triage/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/xadmin/ios-triage/node_modules/through/index.js:74:5)`

That directory had the following files: ExcResource_FlightApp Phone FREE_2016-07-27-093907_iPhone.ips and ExcResource_FlightApp Phone FREE_2016-07-27-093907_iPhone.ips.

**Comment by ahoog42** [comment]
Looks like ios-triage is not handling spaces in file names properly. Thx for filing the bug. I'll test it out and try to push a fix when I next tinker.

**Comment by ahoog42** [comment]
I was splitting lines based on a space which meant I didn't get the whole file name. This has been fixed. Please do a `git pull` to grab the latest code. If you dowloaded a zip file instead, please download the updated one and follow the install directions (unzip, `npm install` and `npm link`).
